//! Configuration structs loaded from CLI args and YAML config.

pub use batch_options::*;
pub use cache_options::*;
pub use config_options::*;
pub use copy_options::*;
pub use cross_config_options::*;
pub use cross_options::*;
pub use file_options::*;
pub(crate) use indexer::*;
pub use qbit_cross_options::*;
pub use qbit_options::*;
pub use qbit_upload_options::*;
pub(crate) use queue_add_args::*;
pub(crate) use queue_fetch_options::*;
pub(crate) use queue_rm_args::*;
pub use report_options::*;
pub(crate) use runner_options::*;
pub(crate) use shared_options::*;
pub(crate) use source_arg::*;
pub(crate) use sox_options::*;
pub use spectrogram_options::*;
pub use target_options::*;
pub use upload_options::*;
pub use verify_options::*;

mod batch_options;
mod cache_options;
mod config_options;
mod copy_options;
mod cross_config_options;
mod cross_options;
mod file_options;
mod indexer;
mod qbit_cross_options;
mod qbit_options;
mod qbit_upload_options;
mod queue_add_args;
mod queue_fetch_options;
mod queue_rm_args;
mod report_options;
mod runner_options;
mod shared_options;
mod source_arg;
mod sox_options;
mod spectrogram_options;
mod target_options;
#[cfg(test)]
mod tests;
mod upload_options;
mod verify_options;
