use std::fmt::Display;

use crate::options::{Command, OptionRule};

/// Trait for partial options structs (generated by the Options derive macro).
///
/// Partial structs have all fields wrapped in `Option<T>`,
/// allowing them to be used with Clap and Serde for CLI/YAML parsing.
pub trait OptionsPartial: Clone + Default + Display + Sized {
    /// The resolved options type.
    type Resolved;

    /// Merge another partial into self (other fills in None/NotSet values).
    fn merge(&mut self, other: &Self);

    /// Deserialize from YAML string.
    fn from_yaml(yaml: &str) -> Result<Self, serde_yaml::Error>;

    /// Get from command line arguments.
    fn from_args() -> Option<Self>;

    /// Resolve partial into final options, applying defaults.
    fn resolve(self) -> Self::Resolved;

    /// Validate the partial options, collecting any errors.
    fn validate(&self, errors: &mut Vec<OptionRule>);
}

/// Trait for resolved options types that declare which commands they apply to.
///
/// This is used by [`OptionsProvider`] to determine which options need validation
/// for a given command.
pub trait ApplicableCommands {
    /// Returns the list of commands this options struct applies to.
    fn applicable_commands() -> &'static [Command];
}
