//! Options trait contracts for the derive macro system.
//!
//! # Usage
//!
//! 1. Define a struct with `#[derive(Options)]`
//! 2. Implement [`OptionsContract`] for it → compiler requires `type Partial: FromArgs`
//! 3. Implement [`FromArgs`] for the partial → compiler enforces this (no default)
//! 4. Macro generates the partial struct and [`OptionsPartialContract`] impl

use crate::commands::CommandArguments;
use crate::options::OptionRule;
use serde::de::DeserializeOwned;

/// Contract for resolved options structs.
///
/// Implement this on the resolved type (e.g., `SharedOptions`).
///
/// The `type Partial: FromArgs` bound enforces that you also implement
/// [`FromArgs`] for the partial type, ensuring the compiler catches
/// any missing implementations.
pub trait OptionsContract: Sized {
    /// The partial type generated by the derive macro.
    type Partial: FromArgs;

    /// Validate the resolved options.
    ///
    /// Appends any validation errors to the provided vector.
    fn validate(&self, errors: &mut Vec<OptionRule>);
}

/// Contract for partial options structs.
///
/// Generated by the `#[derive(Options)]` macro on the partial type
/// (e.g., `SharedOptionsPartial`). This is what the macro produces.
pub trait OptionsPartialContract: Clone + Default + DeserializeOwned + FromArgs + Sized {
    /// The resolved options type.
    type Resolved: OptionsContract;

    /// Merge another partial into self (other fills in None/NotSet values).
    fn merge(&mut self, other: Self);

    /// Resolve partial into final options, applying defaults.
    ///
    /// Does not check required fields or run validation.
    /// Use `resolve()` for full validation.
    fn resolve_without_validation(self) -> Self::Resolved;

    /// Resolve partial into final options with validation.
    ///
    /// Checks required fields are present and runs validation.
    /// Returns `Err` with all validation errors if any checks fail.
    fn resolve(self) -> Result<Self::Resolved, Vec<OptionRule>>;
}

/// Trait for extracting partial options from CLI arguments.
///
/// Implemented on the partial type (e.g., `SharedOptionsPartial`).
/// Must be manually implemented - the compiler will error if missing.
pub trait FromArgs: Sized {
    /// Extract options from CLI arguments.
    ///
    /// Returns `None` if the current command doesn't use these options.
    #[expect(clippy::ref_option, reason = "callers have Option<T>, not &T")]
    fn from_args(args: &Option<CommandArguments>) -> Option<Self>;
}
