name: On Push
on:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:

  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - id: release
      env:
        GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: ${{ secrets.RELEASE_SCRIPT }}

    - run: echo "${{ steps.release.outputs.version}}"

    - run: cat "release-notes.md"

    - uses: actions/upload-artifact@v4
      with:
        name: release-notes.md
        path: release-notes.md

    - run: /home/linuxbrew/.linuxbrew/bin/brew install cargo-edit
      if: ${{ steps.release.outputs.version != ''}}

    - run: /home/linuxbrew/.linuxbrew/bin/cargo-set-version set-version ${{ steps.release.outputs.version }}
      if: ${{ steps.release.outputs.version != ''}}

    - run: git --no-pager diff --color

    - uses: actions/upload-artifact@v4
      with:
        name: Cargo.toml
        path: Cargo.toml


  cargo-build:
    runs-on: ubuntu-latest
    needs:
    - release
    steps:

    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: Cargo.toml

    - run: git --no-pager diff --color

    - id: cache-samples
      uses: actions/cache@v4
      with:
       path: samples/content
       key: cache-samples

    - if: steps.cache-samples.outputs.cache-hit != 'true'
      run: ./samples/download-sample

    - run: |
        curl "https://github.com/casey/intermodal/releases/download/v0.1.14/imdl-v0.1.14-x86_64-unknown-linux-musl.tar.gz" \
          --location \
          --show-error \
          --silent \
        | tar \
          --extract \
          --gzip \
          --directory "/usr/local/bin" \
          --file - \
          "imdl"

    - run: sudo apt-get update

    - run: sudo apt-get install flac lame sox imagemagick --yes

    - run: cargo build --release

    - run: cargo test --release --no-fail-fast
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SOURCE: ${{ secrets.SOURCE }}

    - run: cargo check --quiet --all-targets --message-format short
      continue-on-error: true

    - run: cargo clippy --quiet --all-targets --message-format short
      continue-on-error: true

    - run: cargo fmt --quiet --check
      continue-on-error: true

    - run: git --no-pager diff --color --exit-code
      continue-on-error: true

    - uses: actions/upload-artifact@v4
      with:
        name: caesura
        path: target/release/caesura


  cargo-publish:
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.version != ''}}
    needs:
    - release
    - cargo-build
    steps:

    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: Cargo.toml

    - run: git --no-pager diff --color

    - run: cargo publish --allow-dirty --no-verify
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}


  github-release:
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.version != ''}}
    needs:
      - release
      - cargo-build
    steps:

    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: release-notes.md

    - name: gh release create
      if: ${{ ! contains(needs.release.outputs.version, '-') }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: >
        gh release create
        "v${{ needs.release.outputs.version }}"
        --title "v${{ needs.release.outputs.version }}"
        --notes-file release-notes.md
        --target ${{ github.ref_name }}

    - name: gh release create --prerelease
      if: ${{ contains(needs.release.outputs.version, '-') }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: >
        gh release create
        "v${{ needs.release.outputs.version }}"
        --title "v${{ needs.release.outputs.version }}"
        --notes-file release-notes.md
        --target ${{ github.ref_name }}
        --prerelease

    - uses: actions/download-artifact@v4
      with:
        name: caesura

    - name: gh release upload
      run: >
        gh release upload
        "v${{ needs.release.outputs.version }}"
        caesura
        --clobber
        --repo "${{ github.repository }}"
      env:
        GH_TOKEN: ${{ github.token }}


  docker-build:
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.version != ''}}
    needs:
    - release
    steps:

    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: Cargo.toml

    - run: git --no-pager diff --color

    - run: echo $GH_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: docker build -t caesura .

    - run: docker tag caesura ghcr.io/rogueoneecho/caesura:${{ needs.release.outputs.version }}

    - run: docker push ghcr.io/rogueoneecho/caesura:${{ needs.release.outputs.version }}


  docker-release:
    runs-on: ubuntu-latest
    if: ${{ ! contains(needs.release.outputs.version, '-') }}
    needs:
    - release
    - cargo-build
    - docker-build
    steps:

    - run: echo $GH_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: docker pull ghcr.io/rogueoneecho/caesura:${{ needs.release.outputs.version }}

    - run: docker tag ghcr.io/rogueoneecho/caesura:${{ needs.release.outputs.version }} ghcr.io/rogueoneecho/caesura:latest

    - run: docker push ghcr.io/rogueoneecho/caesura:latest
