name: On Push
on:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - id: release
      env:
        GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: ${{ secrets.RELEASE_SCRIPT }}
    - run: echo "${{ steps.release.outputs.version}}"
    - run: cat "release-notes.md"
    - id: cache-samples
      uses: actions/cache@v4
      with:
       path: samples/content
       key: cache-samples
    - if: steps.cache-samples.outputs.cache-hit != 'true'
      run: ./samples/download-sample
    - run: sudo apt-get update
    - run: sudo apt-get install flac lame sox imagemagick --yes
    - run: cargo install imdl
    - run: cargo build
    - run: cargo test --no-fail-fast
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SOURCE: ${{ secrets.SOURCE }}
    - run: cargo check --quiet --all-targets --message-format short
      continue-on-error: true
    - run: cargo clippy --quiet --all-targets --message-format short
      continue-on-error: true
    - run: cargo fmt --quiet --check
      continue-on-error: true
